# Generated by Django 2.2.5 on 2019-10-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='投票主題'),
        ),
    ]
